[build]
builder = "nixpacks"
buildCommand = "bun install && bun run build"

[deploy]
startCommand = "bun run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[nixpacks]
phase.setup = "bun install"
phase.build = "bun run build"
phase.start = "bun run start"